"""List all items name to be downloaded and their destination folder
"""

RAW_DECORATION = "ALGAE, CLOUD, FLOWER, FOLIAGE, GRASS, LADDER, LILY, PLANK, REED, ROAD, SPROUT, TILE, TRACK, VINE"
DECORATION = {r for r in RAW_DECORATION.split(', ')}

RAW_OBSTACLE = "BED, BOG, BOMB, BRICK, CHAIR, CLIFF, DOOR, FENCE, FORT, GATE, HEDGE, HOUSE, HUSK, HUSKS, LOCK, MONITOR, PIANO, PILLAR, PIPE, ROCK, RUBBLE, SHELL, SIGN, SPIKE, STATUE, STUMP, TABLE, TOWER, TREE, TREES, WALL"
OBSTACLE = {r for r in RAW_OBSTACLE.split(', ')}

RAW_PNJ = "BABA, BADBAD, BAT, BEE, BIRD, BUG, BUNNY, CAT, CRAB, DOG, FISH, FOFO, FROG, GHOST, IT, JELLY, JIJI, KEKE, LIZARD, ME, MONSTER, ROBOT, SNAIL, SKULL, TEETH, TURTLE, WORM"
PNJ = {r for r in RAW_PNJ.split(', ')}

RAW_ITEMS = "BOOK, BOLT, BOX, CASH, CLOCK, COG, CRYSTAL, CUP, DRUM, FLAG, GEM, GUITAR, HIHAT, KEY, LAMP, LEAF, MIRROR, MOON, ORB, PANTS, PAPER, PLANET, RING, ROSE, SAX, SCISSORS, SEED, SHIRT, SHOVEL, STAR, STICK, SUN, SWORD, TRUMPET, VASE"
ITEMS = {r for r in RAW_ITEMS.split(', ')}

RAW_FOOD = "BANANA, BOBA, BOTTLE, BURGER, CAKE, CHEESE, DONUT, DRINK, EGG, FRUIT, FUNGUS, FUNGI, LOVE, PIZZA, POTATO, PUMPKIN, TURNIP"
FOOD = {r for r in RAW_FOOD.split(', ')}

INTERMITTENTS = {"BUBBLE", "DUST"}

DESTINATION = {
    "scenery": DECORATION,
    "obstacle": OBSTACLE,
    "items": ITEMS,
    "food": FOOD,
    "pnj": PNJ
}
